# Daniel Malczyk
# ThinkBig Analytics, a Teradata Company

#basic image with CentOS and latest JDK
FROM docker.elastic.co/elasticsearch/elasticsearch:5.4.1

MAINTAINER Daniel Malczyk <dmalczyk@gmail.com>

ADD install/setup/elasticsearch/elasticsearch.yml /usr/share/elasticsearch/config/

USER root
RUN chown elasticsearch:elasticsearch config/elasticsearch.yml
USER elasticsearch