# Daniel Malczyk
# ThinkBig Analytics, a Teradata Company

#starting from NiFi image
FROM dmalczyk/kylo-hadoop:latest

MAINTAINER Daniel Malczyk <dmalczyk@gmail.com>

#add kylo user
RUN /bin/bash -c 'useradd -r -m -s /bin/bash kylo;'

#download and install Kylo rpm
RUN /bin/bash -c 'echo \"Downloading the RPM\";\
wget http://bit.ly/2r4P47A -O kylo-0.8.1-1.rpm;\
rpm -ivh kylo-0.8.1-1.rpm;\
rm kylo-0.8.1-1.rpm'

#setup Kylo database, service mariadb
RUN echo "Setup Kylo database in MySQL" && \
    /opt/kylo/setup/sql/mysql/setup-mysql.sh mariadb root hadoop

#install Kylo components to NiFi (and possibly start NiFi service)
RUN echo "Install Kylo components to NiFi" && \
    /opt/kylo/setup/nifi/install-kylo-components.sh

RUN echo "Creating the dropzone folder" && mkdir -p /var/dropzone
RUN chown nifi:nifi /var/dropzone
RUN chmod 774 /var/dropzone/

#sample data to run after kylo start
COPY sample_data/* /var/sampledata/
RUN chown -R kylo:kylo /var/sampledata

#setup kylo
ENV KYLO_HOME=/opt/kylo
ENV PATH $PATH:$KYLO_HOME
COPY conf/application.properties /opt/kylo/kylo-services/conf/
# Align the same security.jwt.key as kylo-ui which is generated in kylo post-installation
RUN jwtkey=$(grep 'security.jwt.key' /opt/kylo/kylo-ui/conf/application.properties | awk -F  "=" '/1/ {print $2}') && sed -i "s/security\.jwt\.key=<insert-256-bit-secret-key-here>/security\.jwt\.key=${jwtkey}/" /opt/kylo/kylo-services/conf/application.properties
RUN echo "Kylo Installation complete"

# add spark and hadoop path to PATH env variable for kylo user
RUN echo "export PATH=$PATH:/usr/java/default/bin:/usr/local/spark/bin:/usr/local/hadoop/bin" >> /etc/profile

# Add kylo and nifi user to supergroup otherwise kylo-spark-shell service which runs as kylo user will not be able to create database in hive.
RUN groupadd supergroup
RUN usermod -a -G supergroup kylo
RUN usermod -a -G supergroup nifi

# shared volume
RUN mkdir -p /var/share
VOLUME /var/share

COPY scripts/bootstrap.sh /etc/kylo_bootstrap.sh
RUN chown root.root /etc/kylo_bootstrap.sh
RUN chmod 700 /etc/kylo_bootstrap.sh

ENTRYPOINT ["/etc/kylo_bootstrap.sh"]

EXPOSE 8400
